name: Android Build
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Force Extract
        run: |
          # Download the source directly
          wget https://github.com/brunodev85/winlator/archive/refs/heads/main.zip
          # Unzip everything directly into the current folder
          unzip -j main.zip "winlator-main/*"
          # Manually list files to confirm gradlew is there
          ls -F

      - name: Build APK
        run: |
          # We force the permission directly
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-Custom-APK
          path: app/build/outputs/apk/release/*.apk
